import  {Product}  from "./types";

export const products: Product[] = 
[
    {
        id: 1,
        title: "Black Women Printed T-shirts",
        image: [ "/picture/t1.jpg"],
        slug: "black-women-printed-t1",
        price: 150,
        discount: 1,
        category: "tops",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 2,
        title: "Black Women Printed Tee",
        image: ["/picture/t2.jpg"],
        slug: "black-women-printed-t3",
        price: 150,
        discount: 0,
        category: "tops",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 3,
        title: "Jewllery1",
        image: ["/picture/jw1.jpg"],
        slug: "Jewllery1",
        price: 150,
        discount: 0,
        category: "accesories",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 4,
        title: "Jewllery2",
        image: ["/picture/jw2.jpg"],
        slug: "JewlleryRing",
        price: 150,
        discount: 0,
        category: "accesories",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 5,
        title: "Men Shoes",
        image: ["/picture/s1.jpg"],
        slug: "Imported-shoes",
        price: 150,
        discount: 0,
        category: "shoes",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 6,
        title: "Jeans",
        image: ["/picture/j1.jpg"],
        slug: "Imported-paints-l",
        price: 150,
        discount: 0,
        category: "paints",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 7,
        title: "Denim Jeans",
        image: ["/picture/j3.jpg"],
        slug: "Imported-Jeans-2",
        price: 150,
        discount: 0,
        category: "paints",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 8,
        title: " Girls Shoes",
        image: ["/picture/s2.jpg"],
        slug: "casual-shoes",
        price: 150,
        discount: 0,
        category: "shoes",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M"],
        color: ["#ffffff", "#000000"],
        qty: 1,
    },
    {
        id: 9,
        title: "Casual-Shoes",
        image: ["/picture/s3.jpg"],
        slug: "casual-shoes-imported",
        price: 150,
        discount: 0,
        category: "shoes",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },{
        id: 10,
        title: "Jewllery",
        image: ["/picture/jw4.jpg"],
        slug: "Jewllery1",
        price: 150,
        discount: 0,
        category: "accesories",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 11,
        title: "Jewllery",
        image: ["/picture/jw3.jpg"],
        slug: "Jewllery-Imported",
        price: 150,
        discount: 0,
        category: "accesories",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 12,
        title: "Black Women Printed Tee",
        image: ["/picture/t3.jpg"],
        slug: "black-women-printed-",
        price: 150,
        discount: 0,
        category: "tops",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
    {
        id: 12,
        title: "Black Women Printed Tee",
        image: ["/picture/top.jpg"],
        slug: "black-women-printed",
        price: 150,
        discount: 0,
        category: "tops",
        description:
            "Best quality tshirt for women. Lorem ipsum dolor sit amet consectetur, adipisicingelit. Incidunt a qui dignissimos cum possimus. Repellendus aut qui et ad impedit.Eaque placeat exercitationem recusandae quas hic delectus fuga quae maxime!",
        size: ["S", "M", "L", "XL"],
        color: ["#ffffff", "#000000", "#e60000"],
        qty: 1,
    },
]